# Домашнее задание "Линейная алгебра. Матрицы".

In [1]:
import numpy as np

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [74]:
N = 9
A1 = np.random.randint(0,N+1, size=(3,3))
A1

array([[8, 0, 2],
       [8, 5, 9],
       [9, 3, 8]])

In [75]:
A2 = np.eye(3)
A2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [76]:
A_sum = A1 + A2
A_sum

array([[9., 0., 2.],
       [8., 6., 9.],
       [9., 3., 9.]])

In [77]:
A3 = np.array([1, 2, 3])
A_dot = np.dot(A_sum,A3)
A_dot

array([15., 47., 42.])

In [78]:
A_t = np.transpose(A_sum)
A_t

array([[9., 8., 9.],
       [0., 6., 3.],
       [2., 9., 9.]])

In [79]:
A_inv = np.linalg.inv(A_sum)
A_inv

array([[ 0.14754098,  0.03278689, -0.06557377],
       [ 0.04918033,  0.3442623 , -0.35519126],
       [-0.16393443, -0.14754098,  0.29508197]])

## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [84]:
m = np.array([[2, 2],
              [1, 3]])
m_eig = np.linalg.eig(m)
m_eig

(array([1., 4.]),
 array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))

### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2! 

In [324]:
m = np.array([[8, 9],
              [7, 8]])
m_det = np.linalg.det(m)
m, m_det

(array([[8, 9],
        [7, 8]]),
 1.0)

In [327]:
m = np.array([[-2, 1],
              [1, -1]])
m_det = np.linalg.det(m)
m, m_det

(array([[-2,  1],
        [ 1, -1]]),
 1.0)

In [472]:
# Функция получения матрицы 2*2 с определителем = 1, и где элементы не равны 0.

def function_matrix():
    N = 10
    ln = []
    for a in range(-N, N+1):
        if a != 0:
            ln.append(a)
    print(ln)
    arr = []
    for i in ln:
        for j in ln:
            for x in ln:
                for y in ln:
                    matrix = np.array([[i,j],[x,y]])
                    A = np.linalg.det(matrix)
                    if round(A, 1) == 1:
                        arr.append(matrix)
    return arr

matrix_random = function_matrix()
matrix_random[np.random.randint(0,len(matrix_random))]

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


array([[-1,  1],
       [ 3, -4]])